apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
spec:
  template:
    spec:
      containers:
        - name: hello-api
          image: ghcr.io/asgermunk-homelab/hello-api:3-8e39b47b-1791494780-dev # {"$imagepolicy": "flux-system:hello-api-dev"}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
